### ISSUE TITLE
Can't get the same MAE/OBO score as  in the paper

### ISSUE THREAD

**Issue by fugjgjguhih** [SvipRepetitionCounting/TransRAC#46] opened 2023-03-14 14:55 UTC
Thanks you for your great work and  dataset.

 I have tried to reproduce the results with the default code using  pretrain weight to test. And I also tried  to transform .mp4 to .npz with tools.video2npz and  uncommented the L131 and used the dataset.RepCountA_Loader. It did improve the performance a lot, but still can't get  the same performance shown in your paper (MAE:0.44 OBO:0.29).  
 I finally got the test result in RepCountA with MAE:0.582 and OBO:0.284.  And I tried  to retrain the model and got the same result (MAE:0.582 OBO:0.284). It  seems to be the same as in this [ issue](https://github.com/SvipRepetitionCounting/TransRAC/issues/39).
My code is

```
import os
from dataset.RepCountA_Loader import MyData
from models.TransRAC import TransferModel
from testing.test_looping import test_loop

N_GPU = 1
device_ids = [i for i in range(N_GPU)]
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
root_path = r'/mnt/disk_2/xiangwei/LLSP/videos'
test_video_dir = 'test'
test_label_dir = 'test.csv'
config = './configs/recognition/swin/swin_tiny_patch244_window877_kinetics400_1k.py'
checkpoint = './pretrained/swin_tiny_patch244_window877_kinetics400_1k.pth'
lastckpt = '/mnt/disk_1/xiangwei/TransRAC-main/transrac_ckpt_pytorch_171.pt'
NUM_FRAME = 64
SCALES = [1,4,8]
test_dataset = MyData(root_path, test_video_dir, test_label_dir, num_frame=NUM_FRAME)
my_model = TransferModel(config=config, checkpoint=checkpoint, num_frames=NUM_FRAME, scales=SCALES, OPEN=False)
NUM_EPOCHS = 1

test_loop(NUM_EPOCHS, my_model, test_dataset, lastckpt=lastckpt)
```

**Comment by CKRainbow** [comment] 2023-03-25 03:29
I have the same problem with you and even the result is similar (MAE:0.582 OBO:0.282)

my torch version is 1.7.0+cu110, I'm not sure if it's the problem

**Comment by Ironieser** [comment] 2023-04-05 14:39
Could you get the same test result by loading our ckpt as #18 shown?

**Comment by fugjgjguhih** [comment] 2023-04-05 14:50
I have loaded your ckpt and run test.py. And it can't get the same test result
![c2b95cdf60ee08876f3dd0c2a42c143](https://user-images.githubusercontent.com/82987076/230118424-9dc45554-c89c-47af-a63a-f21eac925a00.jpg)

**Comment by Ironieser** [comment] 2023-04-05 15:00
> I have loaded your ckpt and run test.py. And it can't get the same test result ![c2b95cdf60ee08876f3dd0c2a42c143](https://user-images.githubusercontent.com/82987076/230118424-9dc45554-c89c-47af-a63a-f21eac925a00.jpg)↳

Sorry for your question.  Refer to #18, #29, and #43.  I think you could check the input data.

**Comment by fugjgjguhih** [comment] 2023-04-05 15:39
Thank you for suggestion,  but i can't figure out what' wrong with input data, i have already uncommented L131  to transform mp4 to npz as #29, #43 mentioned, and loaded your ckpt as #18 suggested. Those suggetions did  work. They help me to improve my result from roughly  MAE:0.68 to  (MAE:0.582 and OBD:0.284) now, but it still can't get the same result. My colleagues ran your code on diffierent mechines, and they also can’t get the same result.

**Comment by Ironieser** [comment] 2023-04-05 16:08
Sorry, I have no idea what went wrong in this case. The author of #43 has told me he solved the reproduce issue by uncommenting L131 as #29 and #18. Because it's the first time some researchers can not reproduce the result after following #43. I cloned this repo again and followed the [install.md]. (https://github.com/SvipRepetitionCounting/TransRAC/blob/main/install.md) to test all the code and found no bugs In the last month.

I think the step of processing data, mp4 to npz, may be the key to the problem.  And we have no test about whether the different torch versions cause trouble. ( I think it won't. XD)
Because we can not reproduce your bugs, we may not be able to provide further assistance with these bugs.

**Comment by fugjgjguhih** [comment] 2023-04-25 07:54
> I followed all the aforementioned settings and still get MAE: 0.582 and OBO： 0.283. (pytorch 1.7.0, mmcv1.4.0, mmcv_full1.7.1 cuda 10.1), and I tested with two different machines, also repeated downloading the dataset and preprocessing the MP4 to npz, but still got the same results.
> 
> And here is one of the error I met: RuntimeError: round_vml_cpu not implemented for 'Long' because of the round function in "count = torch.sum(target, dim=1).round().to(device)", line 38 in test_lopping.py. I found that one of the video has groundtruth of 0, and if I ignore the round function for that video, I got the result as mentioned above.

This problem seems lies in cuda.  I updated the cuda version from 11.4 to 11.6 and installed pytorch 1.12.1 as well as mmaction2 , then it produced a similar result with the paper.  But I can't figure out the reason and there is still a very small margin to the paper

**Comment by ZYQbill** [comment] 2023-05-23 10:13
Glad to see you have solved it.

Closed as no update.

**Closed by ZYQbill** 2023-05-23 10:13 UTC
Labels: bug

**Comment by jh-yi** [comment] 2023-10-19 13:41
> > I followed all the aforementioned settings and still get MAE: 0.582 and OBO： 0.283. (pytorch 1.7.0, mmcv1.4.0, mmcv_full1.7.1 cuda 10.1), and I tested with two different machines, also repeated downloading the dataset and preprocessing the MP4 to npz, but still got the same results.
> > And here is one of the error I met: RuntimeError: round_vml_cpu not implemented for 'Long' because of the round function in "count = torch.sum(target, dim=1).round().to(device)", line 38 in test_lopping.py. I found that one of the video has groundtruth of 0, and if I ignore the round function for that video, I got the result as mentioned above.
> 
> This problem seems lies in cuda. I updated the cuda version from 11.4 to 11.6 and installed pytorch 1.12.1 as well as mmaction2 , then it produced a similar result with the paper. But I can't figure out the reason and there is still a very small margin to the paper

I have tried this version but still I got MAE=0.5826 and OBO=0.2829. Could you please share with us what is the result you get? Thanks a lot in advance!
